# Generated by Django 5.2.5 on 2025-08-15 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('fill_blank', 'Fill in the Blank')], default='multiple_choice', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('organizational', 'Organizational'), ('public', 'Public'), ('private', 'Private')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('organization-only', 'Organization Only'), ('private', 'Private')], max_length=20)),
                ('pricing_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('subscription', 'Subscription')], default='free', max_length=20)),
                ('pricing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pricing_currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('target_audience', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('estimated_duration', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('language', models.CharField(default='en', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('total_attempts', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_packages', to='hpo_app.player')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_packages', to='hpo_app.organisation')),
                ('questions', models.ManyToManyField(blank=True, related_name='packages', to='hpo_app.question')),
            ],
            options={
                'verbose_name': 'Question Package',
                'verbose_name_plural': 'Question Packages',
            },
        ),
        migrations.CreateModel(
            name='PublicPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensing_type', models.CharField(choices=[('open', 'Open'), ('commercial', 'Commercial'), ('educational', 'Educational')], default='open', max_length=20)),
                ('attribution_required', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('base_package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_details', to='hpo_app.questionpackage')),
            ],
            options={
                'verbose_name': 'Public Package',
                'verbose_name_plural': 'Public Packages',
            },
        ),
        migrations.CreateModel(
            name='PackageAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(blank=True, help_text='Time in seconds', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_attempts', to='hpo_app.player')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='hpo_app.questionpackage')),
            ],
            options={
                'verbose_name': 'Package Attempt',
                'verbose_name_plural': 'Package Attempts',
            },
        ),
        migrations.CreateModel(
            name='OrganizationalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('compliance_required', models.BooleanField(default=False)),
                ('compliance_deadline', models.DateTimeField(blank=True, null=True)),
                ('certification_level', models.CharField(blank=True, max_length=100, null=True)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('allowed_departments', models.JSONField(blank=True, default=list)),
                ('specific_users', models.ManyToManyField(blank=True, related_name='specific_packages', to='hpo_app.player')),
                ('base_package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizational_details', to='hpo_app.questionpackage')),
            ],
            options={
                'verbose_name': 'Organizational Package',
                'verbose_name_plural': 'Organizational Packages',
            },
        ),
    ]
