# Generated by Django 4.2.23 on 2025-08-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='card',
            field=models.CharField(blank=True, choices=[('S3', 'Spades 3'), ('S4', 'Spades 4'), ('S5', 'Spades 5'), ('S6', 'Spades 6'), ('S7', 'Spades 7'), ('SJ', 'Spades Jack'), ('SQ', 'Spades Queen'), ('SK', 'Spades King'), ('SA', 'Spades Ace'), ('H3', 'Hearts 3'), ('H4', 'Hearts 4'), ('H5', 'Hearts 5'), ('H6', 'Hearts 6'), ('H7', 'Hearts 7'), ('HJ', 'Hearts Jack'), ('HQ', 'Hearts Queen'), ('HK', 'Hearts King'), ('HA', 'Hearts Ace'), ('C3', 'Clubs 3'), ('C4', 'Clubs 4'), ('C5', 'Clubs 5'), ('C6', 'Clubs 6'), ('C7', 'Clubs 7'), ('CJ', 'Clubs Jack'), ('CQ', 'Clubs Queen'), ('CK', 'Clubs King'), ('CA', 'Clubs Ace'), ('D3', 'Diamonds 3'), ('D4', 'Diamonds 4'), ('D5', 'Diamonds 5'), ('D6', 'Diamonds 6'), ('D7', 'Diamonds 7'), ('DJ', 'Diamonds Jack'), ('DQ', 'Diamonds Queen'), ('DK', 'Diamonds King'), ('DA', 'Diamonds Ace')], help_text='Associate this question with a playing card', max_length=3, null=True),
        ),
    ]
