# Generated by Django 4.2.23 on 2025-08-21 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0004_question_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to='hpo_app.admin'),
        ),
    ]
