# Generated by Django 5.2.5 on 2025-08-22 18:04

from django.db import migrations, models
import django.core.validators


def migrate_player_names(apps, schema_editor):
    """Combine first_name and last_name into player_name"""
    Player = apps.get_model('hpo_app', 'Player')
    for player in Player.objects.all():
        if hasattr(player, 'first_name') and hasattr(player, 'last_name'):
            player.player_name = f"{player.first_name} {player.last_name}".strip() or "Unknown Player"
            player.save()


def reverse_migrate_player_names(apps, schema_editor):
    """Split player_name back to first_name and last_name"""
    Player = apps.get_model('hpo_app', 'Player')
    for player in Player.objects.all():
        if hasattr(player, 'player_name'):
            name_parts = player.player_name.split(' ', 1)
            player.first_name = name_parts[0] if len(name_parts) > 0 else ''
            player.last_name = name_parts[1] if len(name_parts) > 1 else ''
            player.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0005_question_created_by'),
    ]

    operations = [
        # Add new fields first
        migrations.AddField(
            model_name='player',
            name='player_name',
            field=models.CharField(default='Unknown Player', help_text='Full name of the player', max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='age_group',
            field=models.CharField(blank=True, choices=[('10-15', '10-15'), ('16-21', '16-21'), ('21-29', '21-29'), ('above', 'Above 29')], help_text='Select age group', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='province',
            field=models.CharField(blank=True, choices=[('Kigali City', 'Kigali City'), ('Northern Province', 'Northern Province'), ('Southern Province', 'Southern Province'), ('Eastern Province', 'Eastern Province'), ('Western Province', 'Western Province')], help_text='Select province in Rwanda', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='district',
            field=models.CharField(blank=True, choices=[('Gasabo', 'Gasabo'), ('Kicukiro', 'Kicukiro'), ('Nyarugenge', 'Nyarugenge'), ('Burera', 'Burera'), ('Gakenke', 'Gakenke'), ('Gicumbi', 'Gicumbi'), ('Musanze', 'Musanze'), ('Rulindo', 'Rulindo'), ('Gisagara', 'Gisagara'), ('Huye', 'Huye'), ('Kamonyi', 'Kamonyi'), ('Muhanga', 'Muhanga'), ('Nyamagabe', 'Nyamagabe'), ('Nyanza', 'Nyanza'), ('Nyaruguru', 'Nyaruguru'), ('Ruhango', 'Ruhango'), ('Bugesera', 'Bugesera'), ('Gatsibo', 'Gatsibo'), ('Kayonza', 'Kayonza'), ('Kirehe', 'Kirehe'), ('Ngoma', 'Ngoma'), ('Nyagatare', 'Nyagatare'), ('Rwamagana', 'Rwamagana'), ('Karongi', 'Karongi'), ('Ngororero', 'Ngororero'), ('Nyabihu', 'Nyabihu'), ('Nyamasheke', 'Nyamasheke'), ('Rubavu', 'Rubavu'), ('Rusizi', 'Rusizi'), ('Rutsiro', 'Rutsiro')], help_text='Select district in Rwanda', max_length=30, null=True),
        ),
        
        # Migrate existing data
        migrations.RunPython(migrate_player_names, reverse_migrate_player_names),
        
        # Remove old fields
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='date_of_birth',
        ),
    ]
