# Generated by Django 5.2.5 on 2025-08-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0006_auto_20250822_1804'),
    ]

    operations = [
        # Remove interests and notes fields from Player model
        migrations.RemoveField(
            model_name='player',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='player',
            name='notes',
        ),
    ]
