# Generated by Django 5.2.5 on 2025-08-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0007_auto_20250822_1815'),
    ]

    operations = [
        # Remove the duplicate organisation field that was causing duplication in admin
        migrations.RemoveField(
            model_name='player',
            name='organisation',
        ),
    ]
