# Generated by Django 4.2.23 on 2025-08-23 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0008_remove_interests_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('participant_count', models.IntegerField(choices=[(1, '1 Player (vs Computer)'), (2, '2 Players'), (4, '4 Players'), (6, '6 Players')], help_text='Number of participants in the game')),
                ('team_count', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('winning_team', models.IntegerField(blank=True, choices=[(1, 'Team 1'), (2, 'Team 2')], null=True)),
                ('cards_in_play', models.JSONField(blank=True, default=list, help_text='List of card IDs used in this game')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField(choices=[(1, 'Team 1'), (2, 'Team 2')], help_text='Which team the player belongs to')),
                ('is_winner', models.BooleanField(default=False)),
                ('marks_earned', models.IntegerField(default=0, help_text='Marks earned (1 per win)')),
                ('lost_card', models.CharField(blank=True, choices=[('S3', 'Spades 3'), ('S4', 'Spades 4'), ('S5', 'Spades 5'), ('S6', 'Spades 6'), ('S7', 'Spades 7'), ('SJ', 'Spades Jack'), ('SQ', 'Spades Queen'), ('SK', 'Spades King'), ('SA', 'Spades Ace'), ('H3', 'Hearts 3'), ('H4', 'Hearts 4'), ('H5', 'Hearts 5'), ('H6', 'Hearts 6'), ('H7', 'Hearts 7'), ('HJ', 'Hearts Jack'), ('HQ', 'Hearts Queen'), ('HK', 'Hearts King'), ('HA', 'Hearts Ace'), ('C3', 'Clubs 3'), ('C4', 'Clubs 4'), ('C5', 'Clubs 5'), ('C6', 'Clubs 6'), ('C7', 'Clubs 7'), ('CJ', 'Clubs Jack'), ('CQ', 'Clubs Queen'), ('CK', 'Clubs King'), ('CA', 'Clubs Ace'), ('D3', 'Diamonds 3'), ('D4', 'Diamonds 4'), ('D5', 'Diamonds 5'), ('D6', 'Diamonds 6'), ('D7', 'Diamonds 7'), ('DJ', 'Diamonds Jack'), ('DQ', 'Diamonds Queen'), ('DK', 'Diamonds King'), ('DA', 'Diamonds Ace')], help_text='Card assigned to losing player', max_length=3, null=True)),
                ('question_answered', models.BooleanField(default=False)),
                ('answer_correct', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='hpo_app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participations', to='hpo_app.player')),
            ],
            options={
                'verbose_name': 'Game Participant',
                'verbose_name_plural': 'Game Participants',
                'unique_together': {('game', 'player')},
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_marks', models.IntegerField(default=0)),
                ('team2_marks', models.IntegerField(default=0)),
                ('result_summary', models.JSONField(default=dict, help_text='Summary of game results, questions asked, answers given')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='hpo_app.game')),
            ],
            options={
                'verbose_name': 'Game Result',
                'verbose_name_plural': 'Game Results',
            },
        ),
        migrations.CreateModel(
            name='GameResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('fun_fact', 'Fun Fact (Winner)'), ('question', 'Question (Loser)')], max_length=20)),
                ('fun_fact_text', models.TextField(blank=True, null=True)),
                ('fun_fact_card', models.CharField(blank=True, max_length=3, null=True)),
                ('player_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hpo_app.game')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hpo_app.gameparticipant')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_responses', to='hpo_app.question')),
            ],
            options={
                'verbose_name': 'Game Response',
                'verbose_name_plural': 'Game Responses',
            },
        ),
    ]
