# Generated by Django 4.2.23 on 2025-08-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0009_game_gameparticipant_gameresult_gameresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='correct_answers',
            field=models.IntegerField(default=0, help_text='Total correct answers in games'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_win_streak',
            field=models.IntegerField(default=0, help_text='Current consecutive wins'),
        ),
        migrations.AddField(
            model_name='player',
            name='games_lost',
            field=models.IntegerField(default=0, help_text='Total number of games lost'),
        ),
        migrations.AddField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(default=0, help_text='Total number of games played'),
        ),
        migrations.AddField(
            model_name='player',
            name='games_won',
            field=models.IntegerField(default=0, help_text='Total number of games won'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_game_played',
            field=models.DateTimeField(blank=True, help_text='Last time player participated in a game', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_game_result',
            field=models.CharField(blank=True, choices=[('won', 'Won'), ('lost', 'Lost')], help_text='Result of the last game played', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='longest_win_streak',
            field=models.IntegerField(default=0, help_text='Longest win streak achieved'),
        ),
        migrations.AddField(
            model_name='player',
            name='questions_answered',
            field=models.IntegerField(default=0, help_text='Total questions answered in games'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_game_marks',
            field=models.IntegerField(default=0, help_text='Total marks earned from games'),
        ),
    ]
