# Generated by Django 4.2.23 on 2025-08-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0010_player_correct_answers_player_current_win_streak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cards_in_play',
        ),
        migrations.AddField(
            model_name='game',
            name='cards_chosen',
            field=models.JSONField(blank=True, default=list, help_text='List of card IDs chosen by losing players'),
        ),
    ]
