# Generated by Django 4.2.23 on 2025-08-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0011_rename_cards_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('english', 'English'), ('kinyarwanda', 'Kinyarwanda'), ('french', 'French'), ('swahili', 'Swahili')], default='english', help_text='Language of the content', max_length=20)),
                ('age_group', models.CharField(choices=[('10-14', '10-14 years'), ('15-19', '15-19 years'), ('20-24', '20-24 years'), ('25+', '25+ years')], help_text='Target age group for this content', max_length=10)),
                ('topic', models.CharField(help_text='Main topic or subject area', max_length=255)),
                ('subtopic', models.CharField(blank=True, help_text='Specific subtopic within the main topic', max_length=255, null=True)),
                ('info', models.TextField(help_text='Main content information or educational material')),
                ('title', models.CharField(help_text='Title or heading for the content', max_length=255)),
                ('content_type', models.CharField(choices=[('educational', 'Educational'), ('fun_fact', 'Fun Fact'), ('trivia', 'Trivia'), ('cultural', 'Cultural'), ('historical', 'Historical'), ('scientific', 'Scientific'), ('general', 'General Knowledge')], default='educational', help_text='Type of content', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Difficulty level of the content', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status of the content', max_length=20)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags for categorization (e.g., 'history, rwanda, culture')", max_length=500, null=True)),
                ('card_association', models.CharField(blank=True, help_text="Optional: Associate with specific card (e.g., 'S3', 'HJ')", max_length=10, null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this content has been viewed')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this content has been used in games')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_game_content', to='hpo_app.admin')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_game_content', to='hpo_app.admin')),
                ('related_question', models.ForeignKey(blank=True, help_text='Optional: Link to a related question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_content', to='hpo_app.question')),
            ],
            options={
                'verbose_name': 'Game Content',
                'verbose_name_plural': 'Game Content',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['language', 'age_group'], name='hpo_app_gam_languag_58a599_idx'), models.Index(fields=['topic', 'subtopic'], name='hpo_app_gam_topic_83c93b_idx'), models.Index(fields=['status'], name='hpo_app_gam_status_74a719_idx'), models.Index(fields=['content_type'], name='hpo_app_gam_content_01aea5_idx')],
            },
        ),
    ]
