# Generated by Django 4.2.23 on 2025-08-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0012_gamecontent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gamecontent',
            name='hpo_app_gam_topic_83c93b_idx',
        ),
        migrations.RemoveField(
            model_name='gamecontent',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='gamecontent',
            name='subtopics',
            field=models.JSONField(blank=True, default=list, help_text="List of subtopics within the main topic (e.g., ['Ancient History', 'Modern History', 'Independence'])"),
        ),
        migrations.AddIndex(
            model_name='gamecontent',
            index=models.Index(fields=['topic'], name='hpo_app_gam_topic_426241_idx'),
        ),
    ]
