# Generated by Django 4.2.23 on 2025-08-24 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0013_remove_gamecontent_hpo_app_gam_topic_83c93b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the subtopic (e.g., 'Ancient History', 'Independence Era')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description of the subtopic', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subtopic is active and can be used')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this subtopic within its parent topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subtopic',
                'verbose_name_plural': 'Subtopics',
                'ordering': ['topic__name', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the topic (e.g., 'History', 'Science', 'Culture')", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the topic', null=True)),
                ('language', models.CharField(choices=[('english', 'English'), ('kinyarwanda', 'Kinyarwanda'), ('french', 'French'), ('swahili', 'Swahili')], default='english', help_text='Language of the topic', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this topic is active and can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['language', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='gamecontent',
            name='hpo_app_gam_languag_58a599_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamecontent',
            name='hpo_app_gam_status_74a719_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamecontent',
            name='hpo_app_gam_content_01aea5_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamecontent',
            name='hpo_app_gam_topic_426241_idx',
        ),
        migrations.RemoveField(
            model_name='gamecontent',
            name='language',
        ),
        migrations.RemoveField(
            model_name='gamecontent',
            name='subtopics',
        ),
        migrations.RemoveField(
            model_name='gamecontent',
            name='topic',
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'language')},
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(help_text='The parent topic this subtopic belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='hpo_app.topic'),
        ),
        migrations.AddField(
            model_name='gamecontent',
            name='subtopic',
            field=models.ForeignKey(blank=True, help_text='The subtopic this content belongs to (REQUIRED)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='hpo_app.subtopic'),
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('topic', 'name')},
        ),
    ]
