# Generated by Django 4.2.23 on 2025-08-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0014_add_topic_subtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecontent',
            name='subtopic',
            field=models.ForeignKey(help_text='The subtopic this content belongs to (REQUIRED)', on_delete=django.db.models.deletion.CASCADE, related_name='content', to='hpo_app.subtopic'),
        ),
        migrations.AddIndex(
            model_name='gamecontent',
            index=models.Index(fields=['subtopic', 'age_group'], name='hpo_app_gam_subtopi_ac10b4_idx'),
        ),
        migrations.AddIndex(
            model_name='gamecontent',
            index=models.Index(fields=['status'], name='hpo_app_gam_status_74a719_idx'),
        ),
        migrations.AddIndex(
            model_name='gamecontent',
            index=models.Index(fields=['content_type'], name='hpo_app_gam_content_01aea5_idx'),
        ),
        migrations.AddIndex(
            model_name='gamecontent',
            index=models.Index(fields=['created_at'], name='hpo_app_gam_created_c8007b_idx'),
        ),
    ]
