# Generated by Django 4.2.23 on 2025-08-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0015_make_subtopic_required'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gamecontent',
            name='hpo_app_gam_subtopi_ac10b4_idx',
        ),
        migrations.AddField(
            model_name='gamecontent',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('kinyarwanda', 'Kinyarwanda'), ('french', 'French'), ('swahili', 'Swahili')], help_text='Choose the language: English, Kinyarwanda, French, or Swahili', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamecontent',
            name='topic',
            field=models.CharField(blank=True, help_text="Enter the main topic (like a title) - e.g., 'History', 'Science', 'Culture'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gamecontent',
            name='age_group',
            field=models.CharField(blank=True, choices=[('10-14', '10-14 years'), ('15-19', '15-19 years'), ('20-24', '20-24 years'), ('25+', '25+ years')], help_text='Select target age group: 10-14, 15-19, 20-24, or 25+', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gamecontent',
            name='info',
            field=models.TextField(help_text='Enter the main content information or educational material'),
        ),
        migrations.AlterField(
            model_name='gamecontent',
            name='subtopic',
            field=models.CharField(blank=True, help_text="Enter the subtopic (like a subtitle) - e.g., 'Independence Era', 'Ancient History'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gamecontent',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title or heading for the content', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='gamecontent',
            index=models.Index(fields=['language', 'age_group'], name='hpo_app_gam_languag_58a599_idx'),
        ),
        migrations.AddIndex(
            model_name='gamecontent',
            index=models.Index(fields=['topic'], name='hpo_app_gam_topic_426241_idx'),
        ),
    ]
