# Generated by Django 4.2.23 on 2025-08-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0016_remove_gamecontent_hpo_app_gam_subtopi_ac10b4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecontent',
            name='subtopics_data',
            field=models.JSONField(blank=True, default=list, help_text="Additional subtopics with their information. Format: [{'subtopic': 'Name', 'info': 'Content'}]"),
        ),
        migrations.AlterField(
            model_name='gamecontent',
            name='info',
            field=models.TextField(help_text='Enter the main content information or educational material for the primary subtopic'),
        ),
        migrations.AlterField(
            model_name='gamecontent',
            name='subtopic',
            field=models.CharField(blank=True, help_text="Enter the main subtopic (like a subtitle) - e.g., 'Independence Era', 'Ancient History'", max_length=255, null=True),
        ),
    ]
