# Generated by Django 4.2.23 on 2025-08-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0017_gamecontent_subtopics_data_alter_gamecontent_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age_group',
            field=models.CharField(blank=True, choices=[('10-14', '10-14'), ('15-19', '15-19'), ('20-24', '20-24'), ('25+', '25+')], help_text='Select age group', max_length=10, null=True),
        ),
    ]
