# Generated by Django 4.2.23 on 2025-08-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0018_update_player_age_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Last time player logged in', null=True),
        ),
    ]
