# Generated by Django 4.2.23 on 2025-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpo_app', '0019_player_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('french', 'French'), ('swahili', 'Swahili'), ('kinyarwanda', 'Kinyarwanda')], default='kinyarwanda', help_text='Language for this question', max_length=20),
        ),
    ]
